version: "3"

services:
  standalone:
    image: apachepulsar/pulsar
    expose:
      - 8080
      - 6650
    ports:
      - "6650:6650"
    environment:
      - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"

  dashboard:
    image: apachepulsar/pulsar-dashboard
    ports:
      - "8081:80"
    depends_on:
      - standalone
    environment:
      - SERVICE_URL=http://standalone:8080

  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - standalone
    environment:
      - SERVICE_URL=http://standalone:8080

  github-integration:
    build: ./github-integration
    depends_on:
      - standalone
    environment:
      - SERVICE_URL=http://standalone:8080
