version: "3"

services:
  pulsar-standalone:
    image: apachepulsar/pulsar
    expose:
      - 8080
      - 6650
    environment:
      - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"

  pulsar-dashboard:
    image: apachepulsar/pulsar-dashboard
    depends_on:
      - pulsar-standalone
    ports:
      - "8081:80"
    environment:
      - SERVICE_URL=http://standalone:8080

  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - pulsar-standalone

  github-service:
    build: ./github_service
    depends_on:
      - pulsar-standalone
